name: Project - Node sum
on:
  pull_request:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        npm install
        npm run build --if-present
        npm test
